#version: "2.1"

services:

  ###############################################################
  #    Functions service
  ###############################################################

  flink-rest-integration:
    build:
      dockerfile: Dockerfile
      context: .
    expose:
      - "1108"

  ###############################################################
  #    StateFun runtime
  ###############################################################

  statefun:
    image: my-flink-image
    ports:
      - "8081:8081"
      - "8090:8090"
      - "8091:8091"
      - "8086:8086"
    depends_on:
      - flink-rest-integration
    volumes:
      - ./module.yaml:/module.yaml